# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

killrchat.security.rememberme.key: KillrChat

cassandra:
    host: localhost
    cql.port: 9042


dev.cassandra:
    folders:
        data: /tmp/killrchat_cassandra/data
        commitlog: /tmp/killrchat_cassandra/commitlog
        saved_caches: /tmp/killrchat_cassandra/saved_caches
