INSERT INTO killrchat.chat_rooms(room_name,creator) VALUES ('starcraft',{firstname:'John',lastname:'DOE',login:'jdoe'});
INSERT INTO killrchat.chat_rooms(room_name,creator) VALUES ('call_of_duty',{firstname:'John',lastname:'DOE',login:'jdoe'});
INSERT INTO killrchat.chat_rooms(room_name,creator) VALUES ('bioshock',{firstname:'John',lastname:'DOE',login:'jdoe'});
INSERT INTO killrchat.chat_rooms(room_name,creator) VALUES ('java',{firstname:'John',lastname:'DOE',login:'jdoe'});
INSERT INTO killrchat.chat_rooms(room_name,creator) VALUES ('scala',{firstname:'John',lastname:'DOE',login:'jdoe'});
INSERT INTO killrchat.chat_rooms(room_name,creator) VALUES ('saas',{firstname:'John',lastname:'DOE',login:'jdoe'});
INSERT INTO killrchat.chat_rooms(room_name,creator) VALUES ('team_jennifer_laurence',{firstname:'John',lastname:'DOE',login:'jdoe'});
INSERT INTO killrchat.chat_rooms(room_name,creator) VALUES ('politics',{firstname:'John',lastname:'DOE',login:'jdoe'});
